"""Render canonical package artifacts from a normalization report."""

from __future__ import annotations

import json
from collections import defaultdict
from datetime import date
from pathlib import Path

from .config import PACKAGE_DIR
from .models import CanonicalNodeRecord, Family, NormalizeReport
from .progress import NullProgressReporter

ROOT_JSON_FILES = {
    "package-manifest.json",
    "map.json",
    "taxonomy.json",
    "sources.json",
    "stats.json",
}


def render_package(
    normalize_report: NormalizeReport,
    output_dir: Path | None = None,
    package_version: str = "0.1.0",
    progress: object | None = None,
) -> Path:
    """Render a canonical package tree."""

    target = output_dir or PACKAGE_DIR
    reporter = progress or NullProgressReporter()
    target.mkdir(parents=True, exist_ok=True)
    (target / "indexes").mkdir(exist_ok=True)
    (target / "auxiliary").mkdir(exist_ok=True)
    (target / "nodes").mkdir(exist_ok=True)

    build_date = date.today().isoformat()
    snapshot_date = max(
        (record.last_verified_at for record in normalize_report.node_records),
        default=build_date,
    )

    write_text(target / "README.md", render_readme())
    write_text(target / "SKILLS.md", render_skills())
    write_json(
        target / "package-manifest.json",
        build_package_manifest(normalize_report, package_version, build_date, snapshot_date),
    )
    write_json(
        target / "map.json",
        [entry.model_dump(mode="json") for entry in sorted(normalize_report.map_entries, key=lambda item: item.id)],
    )
    write_text(target / "map.md", render_map_markdown(normalize_report.node_records))
    write_json(target / "taxonomy.json", build_taxonomy())
    write_json(target / "sources.json", build_sources(normalize_report))
    write_json(target / "stats.json", build_stats(normalize_report.node_records))
    render_indexes(normalize_report, target / "indexes")
    render_auxiliary(target / "auxiliary")
    reporter.stage("Render package", detail=f"{len(normalize_report.node_records)} node artifacts")
    render_nodes(normalize_report.node_records, target, progress=reporter)
    return target


def build_package_manifest(
    normalize_report: NormalizeReport,
    package_version: str,
    build_date: str,
    snapshot_date: str,
) -> dict:
    families = sorted({record.family for record in normalize_report.node_records})
    return {
        "package_name": "n8n-nodes-knowledge",
        "package_version": package_version,
        "schema_version": "1.0.0",
        "source_vendor": "n8n",
        "source_base": "https://docs.n8n.io/",
        "build_date": build_date,
        "documentation_snapshot_date": snapshot_date,
        "coverage_status": "partial",
        "language": "en",
        "default_formats": ["markdown", "json"],
        "taxonomy_version": "1.0.0",
        "node_count": len(normalize_report.node_records),
        "included_families": families,
        "notes": "Generated by the collector render step.",
    }


def build_taxonomy() -> dict:
    return {
        "families": ["core", "action", "trigger", "cluster_root", "cluster_sub"],
        "views": ["service", "capability", "type", "category"],
    }


def build_sources(normalize_report: NormalizeReport) -> list[dict]:
    return [
        record.model_dump(mode="json")
        for record in sorted(normalize_report.source_records, key=lambda item: (item.node_id, item.url))
    ]


def build_stats(node_records: list[CanonicalNodeRecord]) -> dict:
    by_family: dict[str, int] = defaultdict(int)
    with_credentials_required = 0
    with_operations_listed = 0
    with_agent_guidance = 0

    for record in node_records:
        by_family[record.family] += 1
        if record.credentials.required:
            with_credentials_required += 1
        if record.operations:
            with_operations_listed += 1
        if any(record.agent_guidance.model_dump(mode="json").values()):
            with_agent_guidance += 1

    return {
        "nodes_total": len(node_records),
        "by_family": dict(sorted(by_family.items())),
        "with_credentials_required": with_credentials_required,
        "with_operations_listed": with_operations_listed,
        "with_agent_guidance": with_agent_guidance,
        "coverage_status": "partial",
    }


def render_indexes(normalize_report: NormalizeReport, indexes_dir: Path) -> None:
    by_name: dict[str, list[str]] = defaultdict(list)
    by_category: dict[str, list[str]] = defaultdict(list)
    by_type: dict[str, list[str]] = defaultdict(list)
    by_service: dict[str, list[str]] = defaultdict(list)
    by_tag: dict[str, list[str]] = defaultdict(list)
    by_capability: dict[str, list[str]] = defaultdict(list)
    by_doc_url: dict[str, str] = {}

    for map_entry, node_record in zip(
        sorted(normalize_report.map_entries, key=lambda item: item.id),
        sorted(normalize_report.node_records, key=lambda item: item.id),
    ):
        by_name[node_record.display_name.lower()].append(node_record.id)
        by_category[node_record.family].append(node_record.id)
        by_type[node_record.family].append(node_record.id)
        if node_record.service is not None:
            by_service[node_record.service].append(node_record.id)
        for tag in node_record.tags:
            by_tag[tag].append(node_record.id)
        for capability in node_record.capabilities:
            by_capability[capability].append(node_record.id)
        by_doc_url[map_entry.doc_url] = map_entry.id

    write_json(indexes_dir / "by-name.json", sort_index_map(by_name))
    write_json(indexes_dir / "by-category.json", sort_index_map(by_category))
    write_json(indexes_dir / "by-type.json", sort_index_map(by_type))
    write_json(indexes_dir / "by-service.json", sort_index_map(by_service))
    write_json(indexes_dir / "by-tag.json", sort_index_map(by_tag))
    write_json(indexes_dir / "by-capability.json", sort_index_map(by_capability))
    write_json(indexes_dir / "by-doc-url.json", dict(sorted(by_doc_url.items())))


def render_auxiliary(auxiliary_dir: Path) -> None:
    write_json(auxiliary_dir / "aliases.json", {})
    write_json(auxiliary_dir / "crosswalks.json", {})
    write_json(auxiliary_dir / "credential-only-nodes.json", [])
    write_json(auxiliary_dir / "deprecated-or-versioned-notes.json", [])


def render_nodes(node_records: list[CanonicalNodeRecord], output_dir: Path, progress: object | None = None) -> None:
    reporter = progress or NullProgressReporter()
    with reporter.task("render", total=len(node_records)) as tracker:
        for record in node_records:
            node_dir = output_dir / node_folder(record.family, record.slug)
            node_dir.mkdir(parents=True, exist_ok=True)
            write_json(node_dir / "node.json", record.model_dump(mode="json"))
            write_text(node_dir / "node.md", render_node_markdown(record))
            tracker.advance(item=record.id)


def node_folder(family: Family, slug: str) -> str:
    if family == Family.ACTION:
        return f"nodes/actions/{slug}"
    if family == Family.TRIGGER:
        return f"nodes/triggers/{slug}"
    if family == Family.CORE:
        return f"nodes/core/{slug}"
    if family == Family.CLUSTER_ROOT:
        return f"nodes/cluster/root/{slug}"
    return f"nodes/cluster/sub/{slug}"


def render_node_markdown(record: CanonicalNodeRecord) -> str:
    return "\n".join(
        [
            f"# {record.display_name}",
            "",
            "## Identity",
            f"- ID: `{record.id}`",
            f"- Family: `{record.family}`",
            f"- Service: `{record.service}`" if record.service is not None else "- Service: `null`",
            "",
            "## Summary",
            record.summary or "Not present in source.",
            "",
            "## When To Use",
            bullet_block(record.when_to_use),
            "",
            "## When Not To Use",
            bullet_block(record.when_not_to_use),
            "",
            "## Credentials",
            f"- Required: `{str(record.credentials.required).lower()}`",
            f"- Notes: {record.credentials.notes or 'Not present in source.'}",
            "",
            "## Operations Or Parameters",
            bullet_block(record.operations or record.node_parameters),
            "",
            "## Inputs And Outputs",
            "Inputs:",
            bullet_block(record.inputs),
            "Outputs:",
            bullet_block(record.outputs),
            "",
            "## Common Issues",
            bullet_block(record.common_issues),
            "",
            "## Limitations And Gotchas",
            "Limitations:",
            bullet_block(record.limitations),
            "Gotchas:",
            bullet_block(record.gotchas),
            "",
            "## Related Nodes",
            bullet_block(record.related_nodes),
            "",
            "## AI Guidance",
            "Selection rules:",
            bullet_block(record.agent_guidance.selection_rules),
            "Disambiguation:",
            bullet_block(record.agent_guidance.disambiguation),
            "Prompt hints:",
            bullet_block(record.agent_guidance.prompt_hints),
            "Retrieval keywords:",
            bullet_block(record.agent_guidance.retrieval_keywords),
            "",
            "## Source",
            f"- URL: {record.doc_url}",
            f"- Last verified: {record.last_verified_at}",
            "",
        ]
    )


def render_map_markdown(node_records: list[CanonicalNodeRecord]) -> str:
    lines = [
        "# Package Map",
        "",
        "## Overview",
        f"- Nodes included: {len(node_records)}",
        "",
        "## Alphabetical Index",
    ]
    for record in sorted(node_records, key=lambda item: item.display_name.lower()):
        lines.append(f"- {record.display_name}")
    return "\n".join(lines) + "\n"


def render_readme() -> str:
    return (
        "# n8n Nodes Knowledge Package\n\n"
        "Generated package for official n8n built-in nodes, intended for human review and machine lookup.\n"
    )


def render_skills() -> str:
    return (
        "# SKILLS.md\n\n"
        "Start with `package-manifest.json`, then `map.json`, then the target `node.json`.\n"
        "Do not invent operations, parameters, or credentials when source fields are empty.\n"
    )


def sort_index_map(index_map: dict[str, list[str]]) -> dict[str, list[str]]:
    return {key: sorted(values) for key, values in sorted(index_map.items())}


def bullet_block(items: list[str]) -> str:
    return "\n".join(f"- {item}" for item in items) if items else "- Not present in source."


def write_json(path: Path, payload: object) -> None:
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def write_text(path: Path, content: str) -> None:
    path.write_text(content if content.endswith("\n") else f"{content}\n", encoding="utf-8")
