"""Render canonical package artifacts from a normalization report."""

from __future__ import annotations

import json
from collections import defaultdict
from datetime import date
from pathlib import Path

from .config import PACKAGE_DIR
from .models import CanonicalNodeRecord, Family, NormalizeReport
from .progress import NullProgressReporter

ROOT_JSON_FILES = {
    "package-manifest.json",
    "map.json",
    "taxonomy.json",
    "sources.json",
    "stats.json",
}


def render_package(
    normalize_report: NormalizeReport,
    output_dir: Path | None = None,
    package_version: str = "0.1.0",
    progress: object | None = None,
) -> Path:
    """Render a canonical package tree."""

    target = output_dir or PACKAGE_DIR
    reporter = progress or NullProgressReporter()
    target.mkdir(parents=True, exist_ok=True)
    (target / "indexes").mkdir(exist_ok=True)
    (target / "auxiliary").mkdir(exist_ok=True)
    (target / "nodes").mkdir(exist_ok=True)

    build_date = date.today().isoformat()
    snapshot_date = max(
        (record.last_verified_at for record in normalize_report.node_records),
        default=build_date,
    )

    write_text(target / "README.md", render_readme())
    write_text(target / "SKILLS.md", render_skills(normalize_report.node_records))
    write_json(
        target / "package-manifest.json",
        build_package_manifest(normalize_report, package_version, build_date, snapshot_date),
    )
    write_json(
        target / "map.json",
        [entry.model_dump(mode="json") for entry in sorted(normalize_report.map_entries, key=lambda item: item.id)],
    )
    write_text(target / "map.md", render_map_markdown(normalize_report.node_records))
    write_json(target / "taxonomy.json", build_taxonomy())
    write_json(target / "sources.json", build_sources(normalize_report))
    write_json(target / "stats.json", build_stats(normalize_report.node_records))
    render_indexes(normalize_report, target / "indexes")
    render_auxiliary(normalize_report.node_records, target / "auxiliary")
    reporter.stage("Render package", detail=f"{len(normalize_report.node_records)} node artifacts")
    render_nodes(normalize_report.node_records, target, progress=reporter)
    return target


def build_package_manifest(
    normalize_report: NormalizeReport,
    package_version: str,
    build_date: str,
    snapshot_date: str,
) -> dict:
    families = sorted({record.family for record in normalize_report.node_records})
    return {
        "package_name": "n8n-nodes-knowledge",
        "package_version": package_version,
        "schema_version": "1.0.0",
        "source_vendor": "n8n",
        "source_base": "https://docs.n8n.io/",
        "build_date": build_date,
        "documentation_snapshot_date": snapshot_date,
        "coverage_status": "partial",
        "language": "en",
        "default_formats": ["markdown", "json"],
        "taxonomy_version": "1.0.0",
        "node_count": len(normalize_report.node_records),
        "included_families": families,
        "notes": "Generated by the collector render step.",
    }


def build_taxonomy() -> dict:
    return {
        "families": ["core", "action", "trigger", "cluster_root", "cluster_sub"],
        "views": ["service", "capability", "type", "category"],
    }


def build_sources(normalize_report: NormalizeReport) -> list[dict]:
    return [
        record.model_dump(mode="json")
        for record in sorted(normalize_report.source_records, key=lambda item: (item.node_id, item.url))
    ]


def build_stats(node_records: list[CanonicalNodeRecord]) -> dict:
    by_family: dict[str, int] = defaultdict(int)
    with_credentials_required = 0
    with_operations_listed = 0
    with_agent_guidance = 0

    for record in node_records:
        by_family[record.family] += 1
        if record.credentials.required:
            with_credentials_required += 1
        if record.operations:
            with_operations_listed += 1
        if any(record.agent_guidance.model_dump(mode="json").values()):
            with_agent_guidance += 1

    return {
        "nodes_total": len(node_records),
        "by_family": dict(sorted(by_family.items())),
        "with_credentials_required": with_credentials_required,
        "with_operations_listed": with_operations_listed,
        "with_agent_guidance": with_agent_guidance,
        "coverage_status": "partial",
    }


def render_indexes(normalize_report: NormalizeReport, indexes_dir: Path) -> None:
    by_name: dict[str, list[str]] = defaultdict(list)
    by_category: dict[str, list[str]] = defaultdict(list)
    by_type: dict[str, list[str]] = defaultdict(list)
    by_service: dict[str, list[str]] = defaultdict(list)
    by_tag: dict[str, list[str]] = defaultdict(list)
    by_capability: dict[str, list[str]] = defaultdict(list)
    by_doc_url: dict[str, str] = {}

    for map_entry, node_record in zip(
        sorted(normalize_report.map_entries, key=lambda item: item.id),
        sorted(normalize_report.node_records, key=lambda item: item.id),
    ):
        by_name[node_record.display_name.lower()].append(node_record.id)
        by_category[node_record.family].append(node_record.id)
        by_type[node_record.family].append(node_record.id)
        if node_record.service is not None:
            by_service[node_record.service].append(node_record.id)
        for tag in node_record.tags:
            by_tag[tag].append(node_record.id)
        for capability in node_record.capabilities:
            by_capability[capability].append(node_record.id)
        by_doc_url[map_entry.doc_url] = map_entry.id

    write_json(indexes_dir / "by-name.json", sort_index_map(by_name))
    write_json(indexes_dir / "by-category.json", sort_index_map(by_category))
    write_json(indexes_dir / "by-type.json", sort_index_map(by_type))
    write_json(indexes_dir / "by-service.json", sort_index_map(by_service))
    write_json(indexes_dir / "by-tag.json", sort_index_map(by_tag))
    write_json(indexes_dir / "by-capability.json", sort_index_map(by_capability))
    write_json(indexes_dir / "by-doc-url.json", dict(sorted(by_doc_url.items())))


def render_auxiliary(node_records: list[CanonicalNodeRecord], auxiliary_dir: Path) -> None:
    write_json(auxiliary_dir / "aliases.json", build_aliases(node_records))
    write_json(auxiliary_dir / "crosswalks.json", build_crosswalks(node_records))
    write_json(auxiliary_dir / "credential-only-nodes.json", [])
    write_json(auxiliary_dir / "deprecated-or-versioned-notes.json", [])


def build_aliases(node_records: list[CanonicalNodeRecord]) -> dict[str, list[str]]:
    aliases: dict[str, list[str]] = defaultdict(list)

    for node in node_records:
        seeds = {
            node.id,
            node.slug,
            node.slug.replace("-", " "),
            node.display_name.lower(),
        }
        if node.service:
            seeds.add(node.service.lower())
        seeds.update(node.tags[:8])

        for alias in sorted(seed for seed in seeds if seed):
            aliases[alias].append(node.id)

    return sort_index_map(aliases)


def build_crosswalks(node_records: list[CanonicalNodeRecord]) -> dict[str, list[dict[str, str]]]:
    http_request_id = next((node.id for node in node_records if node.slug == "http-request"), None)
    cluster_roots = [node.id for node in node_records if node.family == Family.CLUSTER_ROOT]
    cluster_subs = [node.id for node in node_records if node.family == Family.CLUSTER_SUB]

    specialized_vs_generic: list[dict[str, str]] = []
    if http_request_id is not None:
        for node in sorted(node_records, key=lambda item: item.id):
            if node.family != Family.ACTION:
                continue
            specialized_vs_generic.append(
                {
                    "specialized": node.id,
                    "generic_alternative": http_request_id,
                    "rule": f"Prefer {node.display_name} for supported native operations; use HTTP Request only for unsupported API needs.",
                }
            )

    cluster_relationships: list[dict[str, str]] = []
    for root_id in cluster_roots:
        for sub_id in cluster_subs[:8]:
            cluster_relationships.append(
                {
                    "root": root_id,
                    "sub": sub_id,
                    "rule": "Cluster sub-nodes extend a compatible AI root node and are not standalone workflow roots.",
                }
            )

    return {
        "specialized_vs_generic": specialized_vs_generic,
        "cluster_relationships": cluster_relationships,
    }


def render_nodes(node_records: list[CanonicalNodeRecord], output_dir: Path, progress: object | None = None) -> None:
    reporter = progress or NullProgressReporter()
    with reporter.task("render", total=len(node_records)) as tracker:
        for record in node_records:
            node_dir = output_dir / node_folder(record.family, record.slug)
            node_dir.mkdir(parents=True, exist_ok=True)
            write_json(node_dir / "node.json", record.model_dump(mode="json"))
            write_text(node_dir / "node.md", render_node_markdown(record))
            tracker.advance(item=record.id)


def node_folder(family: Family, slug: str) -> str:
    if family == Family.ACTION:
        return f"nodes/actions/{slug}"
    if family == Family.TRIGGER:
        return f"nodes/triggers/{slug}"
    if family == Family.CORE:
        return f"nodes/core/{slug}"
    if family == Family.CLUSTER_ROOT:
        return f"nodes/cluster/root/{slug}"
    return f"nodes/cluster/sub/{slug}"


def render_node_markdown(record: CanonicalNodeRecord) -> str:
    return "\n".join(
        [
            f"# {record.display_name}",
            "",
            "## Identity",
            f"- ID: `{record.id}`",
            f"- Family: `{record.family}`",
            f"- Service: `{record.service}`" if record.service is not None else "- Service: `null`",
            "",
            "## Summary",
            record.summary or "Not present in source.",
            "",
            "## When To Use",
            bullet_block(record.when_to_use),
            "",
            "## When Not To Use",
            bullet_block(record.when_not_to_use),
            "",
            "## Credentials",
            f"- Required: `{str(record.credentials.required).lower()}`",
            f"- Notes: {record.credentials.notes or 'Not present in source.'}",
            "",
            "## Operations Or Parameters",
            bullet_block(record.operations or record.node_parameters),
            "",
            "## Inputs And Outputs",
            "Inputs:",
            bullet_block(record.inputs),
            "Outputs:",
            bullet_block(record.outputs),
            "",
            "## Common Issues",
            bullet_block(record.common_issues),
            "",
            "## Limitations And Gotchas",
            "Limitations:",
            bullet_block(record.limitations),
            "Gotchas:",
            bullet_block(record.gotchas),
            "",
            "## Related Nodes",
            bullet_block(record.related_nodes),
            "",
            "## AI Guidance",
            "Selection rules:",
            bullet_block(record.agent_guidance.selection_rules),
            "Disambiguation:",
            bullet_block(record.agent_guidance.disambiguation),
            "Prompt hints:",
            bullet_block(record.agent_guidance.prompt_hints),
            "Retrieval keywords:",
            bullet_block(record.agent_guidance.retrieval_keywords),
            "",
            "## Source",
            f"- URL: {record.doc_url}",
            f"- Last verified: {record.last_verified_at}",
            "",
        ]
    )


def render_map_markdown(node_records: list[CanonicalNodeRecord]) -> str:
    lines = [
        "# Package Map",
        "",
        "## Overview",
        f"- Nodes included: {len(node_records)}",
        "",
        "## Alphabetical Index",
    ]
    for record in sorted(node_records, key=lambda item: item.display_name.lower()):
        lines.append(f"- {record.display_name}")
    return "\n".join(lines) + "\n"


def render_readme() -> str:
    return (
        "# n8n Nodes Knowledge Package\n\n"
        "Generated package for official n8n built-in nodes, intended for human review and machine lookup.\n"
    )


def render_skills(node_records: list[CanonicalNodeRecord]) -> str:
    family_counts: dict[str, int] = defaultdict(int)
    for node in node_records:
        family_counts[node.family] += 1

    return "\n".join(
        [
            "# SKILLS.md",
            "",
            "## Purpose",
            "",
            "This package is a structured knowledge base for official n8n nodes.",
            "Use it to resolve nodes quickly, recommend the best-fit node, compare alternatives, and avoid hallucinated capabilities.",
            "",
            "## Scope",
            "",
            "The corpus covers official built-in nodes collected from the n8n docs snapshot represented by `package-manifest.json`.",
            "Treat freshness and completeness as bounded by `coverage_status`, `build_date`, `documentation_snapshot_date`, and each node's `last_verified_at`.",
            "",
            "## Canonical Lookup Order",
            "",
            "1. Read `package-manifest.json` to understand scope and freshness.",
            "2. Resolve candidates through `collector resolve <package-dir> \"<query>\"` when the CLI is available.",
            "3. If resolving manually, use `map.json` and `indexes/*`.",
            "4. Use `auxiliary/aliases.json` and `auxiliary/crosswalks.json` for renamed, related, or specialized-vs-generic routing.",
            "5. Open the selected `node.json` as the canonical structured source.",
            "6. Use `node.md` only for narrative explanation after `node.json` is already resolved.",
            "",
            "Do not scan package folders blindly when an index or alias file can answer the question directly.",
            "",
            "## Retrieval Strategy",
            "",
            "When resolving a request, prefer this order:",
            "1. exact `id`",
            "2. exact `slug`",
            "3. exact `display_name`",
            "4. exact `service` match via `indexes/by-service.json`",
            "5. alias match via `auxiliary/aliases.json`",
            "6. capability and tag match via `indexes/by-capability.json` and `indexes/by-tag.json`",
            "",
            "## Specialized-First Policy",
            "",
            "Prefer specialized app nodes over generic nodes when the specialized node covers the requested operation.",
            "Use `HTTP Request` only as a fallback when the specialized node does not expose the needed operation or the package guidance explicitly says to fall back.",
            "If a user mentions a service directly, search that service first. Example: for Odoo work, resolve the Odoo node before considering generic API calls.",
            "",
            "## Disambiguation Rules",
            "",
            "- Distinguish action nodes from trigger nodes. Trigger nodes start workflows; action nodes perform work inside a running workflow.",
            "- Distinguish app nodes from core nodes. Core nodes express workflow logic or generic protocol access.",
            "- Distinguish `cluster_root` from `cluster_sub`. Sub-nodes are not standalone roots.",
            "- When several matches exist, rank exact service and specialized capability matches above generic alternatives.",
            "",
            "## Concurrent Usage Guidance",
            "",
            "For fast agent usage, do not expand every node. Query indexes in parallel, merge candidates, score them, then open only the top few `node.json` records.",
            "A good default is concurrent lookup across `by-name`, `by-service`, `by-tag`, `by-capability`, and `aliases`, followed by concurrent expansion of the top 3 to 5 candidate node files.",
            "The repository CLI already implements this pattern through `collector resolve <package-dir> \"<query>\" --limit 5 --expand-concurrency 8`.",
            "",
            "## Response Policy",
            "",
            "- Separate extracted facts from derived guidance.",
            "- Do not invent operations, parameters, credentials, or compatibility when fields are empty.",
            "- Prefer canonical `display_name` and `id` values over guessed naming.",
            "- Mention uncertainty when freshness is partial or the package lacks the required field.",
            "",
            "## Suggested Answer Patterns",
            "",
            "For `Which node should I use?`: best-fit node, why it fits, second-best alternative, and fallback guidance if needed.",
            "For `Compare these nodes`: family, execution role, credentials, operations or parameters, limitations, and best-fit scenarios.",
            "For `How do I use this node?`: summary, credentials, operations or parameters, pitfalls, and related nodes.",
            "",
            "## Package Snapshot",
            "",
            f"- Nodes included: {len(node_records)}",
            f"- Families included: {', '.join(f'{family}={count}' for family, count in sorted(family_counts.items()))}",
            "",
        ]
    ) + "\n"


def sort_index_map(index_map: dict[str, list[str]]) -> dict[str, list[str]]:
    return {key: sorted(values) for key, values in sorted(index_map.items())}


def bullet_block(items: list[str]) -> str:
    return "\n".join(f"- {item}" for item in items) if items else "- Not present in source."


def write_json(path: Path, payload: object) -> None:
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def write_text(path: Path, content: str) -> None:
    path.write_text(content if content.endswith("\n") else f"{content}\n", encoding="utf-8")
